import Head from "next/head";
import { Inter } from "@next/font/google";
import { NextPage } from "next/types";
import { useQuery } from "@apollo/client";
import { graphql } from "../graphql/generated/client";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

const PhisicalStates = graphql(`
  query PhisicalStates {
    phisicalStates {
      id
      name
      description
    }
  }
`);

const Home: NextPage = () => {
  const { loading, error, data } = useQuery(PhisicalStates);

  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={inter.className}>
        <p className="text-blue-800 text-2xl font-medium">Quantum</p>

        <div>
          {loading ? (
            <p>Loading...</p>
          ) : error ? (
            <>
              <p>Something went wrong.</p>
              <p>{JSON.stringify(error)}</p>
            </>
          ) : (
            <div>{JSON.stringify(data?.phisicalStates)}</div>
          )}
        </div>
      </div>
    </>
  );
};

export default Home;
